---
# handlers file for pacman

- name: reboot machine
  listen: reboot
  become: true
  reboot:
    msg: "rebooting from ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0 
    post_reboot_delay: 30
    test_command: uname  -a 
    